### ISSUE TITLE
您好！能添加多几个中文源吗？

### ISSUE THREAD

**Issue by DevCoz** [getBoolean/PB-Chinese-Extensions#1]
找了很久，都没有找到中文源，只有您这个源，希望能添加多几个中文源。感谢。
https://www.baozimh.com
https://18comic.vip
https://www.cocomanga.com

**Comment by getBoolean** [comment]
谢谢你的建议。如果我有时间，我会考虑它们。
翻译：DeepL

Thank you for the suggestions. I will consider them if I have time.

**Comment by DevCoz** [comment]
thank you very much.

**Comment by echovvv** [comment]
您好！想请教一下这个该输入什么链接才能加到paperback中阅读

**Comment by getBoolean** [comment]
> 您好！想请教一下这个该输入什么链接才能加到paperback中阅读

My current extensions do not work with the latest version of paperback. I plan to update it in my free time.

**Comment by echovvv** [comment]
Thank you very much for your reply :)
